# Generated by Django 5.2.8 on 2025-11-14 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='instituicao',
        ),
        migrations.AddField(
            model_name='professor',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
