# Generated by Django 5.2.8 on 2025-11-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_remove_professor_instituicao_professor_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='usuario',
            new_name='criado_por',
        ),
        migrations.AddField(
            model_name='matricula',
            name='data_cancelamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='status_matricula',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('desistente', 'Desistente'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='ativa', max_length=60),
        ),
    ]
