# Generated by Django 5.2.8 on 2025-11-14 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_rename_usuario_matricula_criado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='ano_letivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrador.anoletivo'),
            preserve_default=False,
        ),
    ]
