# Generated by Django 5.2.8 on 2025-11-14 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_matricula_ano_letivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrador.classe'),
            preserve_default=False,
        ),
    ]
