# Generated by Django 5.2.8 on 2025-11-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_turma_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='ano_escolar',
        ),
    ]
