# Generated by Django 5.2.8 on 2025-11-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_remove_turma_ano_escolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaprofessor',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
