# Generated by Django 5.2.8 on 2025-11-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_disciplinaprofessor_abreviatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinaprofessor',
            name='abreviatura',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
