# Generated by Django 5.2.8 on 2025-11-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0010_remove_disciplinaprofessor_abreviatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinaprofessor',
            name='turma',
        ),
    ]
