# Generated by Django 5.2.8 on 2025-11-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_remove_disciplinaprofessor_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrador.professor'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DisciplinaProfessor',
        ),
    ]
