# Generated by Django 5.2.8 on 2025-11-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0012_disciplina_professor_delete_disciplinaprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='not_Ev_Sist3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
