# Generated by Django 5.2.8 on 2025-11-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0013_resultado_not_ev_sist3'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoletivo',
            name='e_atual',
            field=models.BooleanField(default=False),
        ),
    ]
