# Generated by Django 5.2.8 on 2025-11-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0014_anoletivo_e_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.anoletivo'),
        ),
    ]
