# Generated by Django 5.2.8 on 2025-11-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0015_turma_ano_letivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='turma',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
