# Generated by Django 5.2.8 on 2025-11-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0016_alter_turma_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='turma',
            field=models.CharField(max_length=4),
        ),
    ]
