# Generated by Django 5.2.8 on 2025-11-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0017_alter_turma_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='provincia',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
