# Generated by Django 5.2.8 on 2025-11-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0018_instituicao_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='instituicao',
        ),
    ]
