# Generated by Django 5.2.8 on 2025-11-24 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0019_remove_classe_instituicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='provincia',
        ),
        migrations.AddField(
            model_name='classe',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrador.instituicao'),
            preserve_default=False,
        ),
    ]
