# Generated by Django 5.2.8 on 2025-11-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0021_alter_role_nome_horarioaula'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioaula',
            name='data_prova',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='tipo',
            field=models.CharField(choices=[('prova', 'Prova'), ('aula', 'Aula')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
