# Generated by Django 5.2.8 on 2025-11-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0022_horarioaula_data_prova_horarioaula_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioaula',
            name='dia_semana',
            field=models.CharField(choices=[('Segunda', 'Segunda-feira'), ('Terça', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'Sexta-feira')], max_length=10),
        ),
    ]
