# Generated by Django 5.2.8 on 2025-11-26 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0024_alter_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioaula',
            name='ano_letivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='administrador.anoletivo'),
            preserve_default=False,
        ),
    ]
