# Generated by Django 5.2.8 on 2025-11-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0025_horarioaula_ano_letivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anoescolar',
            name='ano_letivo',
        ),
        migrations.RemoveField(
            model_name='anoescolar',
            name='classe',
        ),
        migrations.DeleteModel(
            name='Habilitacao',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='AnoEscolar',
        ),
        migrations.DeleteModel(
            name='Instituicao',
        ),
    ]
