# Generated by Django 5.2.8 on 2025-11-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0026_remove_anoescolar_ano_letivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='role',
            name='nome',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Diretor'), (3, 'Secretário')], max_length=90),
        ),
    ]
