# Generated by Django 5.2.8 on 2025-11-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0027_remove_estudante_usuario_alter_role_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudante',
            name='emitido_em',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudante',
            name='nome_mae',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudante',
            name='nome_pai',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudante',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
