# Generated by Django 5.2.8 on 2025-11-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0028_estudante_data_emissao_estudante_emitido_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
    ]
