# Generated by Django 5.2.8 on 2025-11-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0029_estudante_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='emitido_em',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
