# Generated by Django 5.2.8 on 2025-11-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0030_alter_estudante_emitido_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudante',
            name='natural',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudante',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
